import { IGalleryItemProps } from "../GalleryItem/GalleryItem.model";

export const OVERVIEW_ITEMS: IGalleryItemProps[] = [
	{
		title: "items.titles.2",
		description: "items.descriptions.2",
		images: ["/gallery/container/1.webp", "/gallery/container/2.webp", "/gallery/container/3.webp"],
		tags: ["overview", "tutorial"],
		type: "image",
		category: "categories.features",
		date: "2026-03-14",
	},
	{
		title: "items.titles.1",
		description: "items.descriptions.1",
		images: [
			"/gallery/seal/1.webp",
			"/gallery/seal/2.webp",
			"/gallery/seal/3.webp",
			"/gallery/seal/4.webp",
			"/gallery/seal/5.webp",
			"/gallery/seal/6.webp",
			"/gallery/seal/7.webp",
			"/gallery/seal/8.webp",
			"/gallery/seal/9.webp",
			"/gallery/seal/10.webp",
			"/gallery/seal/11.webp",
		],
		tags: ["overview", "tutorial"],
		type: "image",
		category: "categories.features",
		date: "2026-03-14",
	},
	{
		title: "items.titles.9",
		description: "items.descriptions.9",
		images: [
			"/gallery/reseal/1.webp",
			"/gallery/reseal/2.webp",
			"/gallery/reseal/3.webp",
			"/gallery/reseal/4.webp",
			"/gallery/reseal/5.webp",
			"/gallery/reseal/6.webp",
			"/gallery/reseal/7.webp",
		],
		tags: ["overview", "tutorial"],
		type: "image",
		category: "categories.features",
		date: "2026-03-14",
	},
	{
		title: "items.titles.10",
		description: "items.descriptions.10",
		images: [
			"/gallery/container_opened/1.webp",
			"/gallery/container_opened/2.webp",
			"/gallery/container_opened/3.webp",
			"/gallery/container_opened/4.webp",
		],
		tags: ["overview", "tutorial"],
		type: "image",
		category: "categories.features",
		date: "2026-03-14",
	},
	{
		title: "items.titles.3",
		description: "items.descriptions.3",
		images: ["/gallery/settings/1.webp", "/gallery/settings/2.webp"],
		tags: ["overview", "tutorial"],
		type: "image",
		category: "categories.features",
		date: "2026-03-14",
	},
];

export const LOGOS_ITEMS: IGalleryItemProps[] = [
	{
		title: "items.titles.4",
		description: "items.descriptions.4",
		images: ["/gallery/logos/tvault_black.png"],
		tags: ["logos", "tvault"],
		type: "image",
		category: "categories.logos",
		date: "2026-03-14",
	},
	{
		title: "items.titles.5",
		description: "items.descriptions.5",
		images: ["/gallery/logos/tvault_blue.png"],
		tags: ["logos", "tvault"],
		type: "image",
		category: "categories.logos",
		date: "2026-03-14",
	},
	{
		title: "items.titles.6",
		description: "items.descriptions.6",
		images: ["/gallery/logos/nameless_1.png"],
		tags: ["logos", "nameless"],
		type: "image",
		category: "categories.logos",
		date: "2026-03-14",
	},
	{
		title: "items.titles.7",
		description: "items.descriptions.7",
		images: ["/gallery/logos/nameless_2.png"],
		tags: ["logos", "nameless"],
		type: "image",
		category: "categories.logos",
		date: "2026-03-14",
	},
	{
		title: "items.titles.8",
		description: "items.descriptions.8",
		images: ["/gallery/logos/nameless_3.png"],
		tags: ["logos", "nameless"],
		type: "image",
		category: "categories.logos",
		date: "2026-03-14",
	},
];
